name: 'ArgoCD Diff'
description: 'Diffs all ArgoCD apps in the repo, and provides the diff as a PR comment'
author: 'Quizlet'
inputs:
  argocd-server-url: 
    description: ArgoCD server url (without the protocol)
    required: true
  argocd-token: 
    description: ArgoCD token for a local or project-scoped user https://argoproj.github.io/argo-cd/operator-manual/user-management/#local-usersaccounts-v15
    required: true
  argocd-version: 
    description: ArgoCD Version
    default: v1.6.1
    required: false
  github-token: 
    description: Github Token
    required: true
  argocd-extra-cli-args: 
    description: Extra arguments to pass to the argocd CLI
    default: --grpc-web
    required: false
  github-user:
    description: "Registry's user"
    required: false
    default: ${{ github.actor }}
  github-password:
    description: "Registry user's password or token"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Log in to Github Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ inputs.github-user }}
        password: ${{ inputs.github-password }}
    - name: Install argocd-lovely-plugin
      run: docker run -v `pwd`/bin/argo/custom-tools:/custom-tools ghcr.io/getprotocollab/argocd-lovely-plugin:latest
      shell: bash
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Run ArgoCD diff
      run: PATH=`pwd`/bin/argo/custom-tools:$PATH node dist/index.js
      shell: bash
